// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package aic.website.domain;

import aic.website.domain.AuthRole;

privileged aspect AuthRole_Roo_JavaBean {
    
    public String AuthRole.getName() {
        return this.name;
    }
    
    public void AuthRole.setName(String name) {
        this.name = name;
    }
    
}
