// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package aic.website.domain;

import aic.website.domain.AuthRole;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AuthRole_Roo_Configurable {
    
    declare @type: AuthRole: @Configurable;
    
}
