// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.ac.tuwien.frontend.website.domain;

import at.ac.tuwien.frontend.website.domain.CloudUser;
import at.ac.tuwien.frontend.website.domain.CloudUserDataOnDemand;
import at.ac.tuwien.frontend.website.domain.CloudUserIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CloudUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CloudUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CloudUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CloudUserIntegrationTest: @Transactional;
    
    @Autowired
    private CloudUserDataOnDemand CloudUserIntegrationTest.dod;
    
    @Test
    public void CloudUserIntegrationTest.testCountCloudUsers() {
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", dod.getRandomCloudUser());
        long count = CloudUser.countCloudUsers();
        Assert.assertTrue("Counter for 'CloudUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CloudUserIntegrationTest.testFindCloudUser() {
        CloudUser obj = dod.getRandomCloudUser();
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to provide an identifier", id);
        obj = CloudUser.findCloudUser(id);
        Assert.assertNotNull("Find method for 'CloudUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CloudUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CloudUserIntegrationTest.testFindAllCloudUsers() {
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", dod.getRandomCloudUser());
        long count = CloudUser.countCloudUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'CloudUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CloudUser> result = CloudUser.findAllCloudUsers();
        Assert.assertNotNull("Find all method for 'CloudUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CloudUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CloudUserIntegrationTest.testFindCloudUserEntries() {
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", dod.getRandomCloudUser());
        long count = CloudUser.countCloudUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CloudUser> result = CloudUser.findCloudUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CloudUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CloudUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CloudUserIntegrationTest.testFlush() {
        CloudUser obj = dod.getRandomCloudUser();
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to provide an identifier", id);
        obj = CloudUser.findCloudUser(id);
        Assert.assertNotNull("Find method for 'CloudUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCloudUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CloudUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CloudUserIntegrationTest.testMergeUpdate() {
        CloudUser obj = dod.getRandomCloudUser();
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to provide an identifier", id);
        obj = CloudUser.findCloudUser(id);
        boolean modified =  dod.modifyCloudUser(obj);
        Integer currentVersion = obj.getVersion();
        CloudUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CloudUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CloudUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", dod.getRandomCloudUser());
        CloudUser obj = dod.getNewTransientCloudUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CloudUser' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'CloudUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CloudUserIntegrationTest.testRemove() {
        CloudUser obj = dod.getRandomCloudUser();
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CloudUser' failed to provide an identifier", id);
        obj = CloudUser.findCloudUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CloudUser' with identifier '" + id + "'", CloudUser.findCloudUser(id));
    }
    
}
