// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.ac.tuwien.frontend.website.domain;

import at.ac.tuwien.frontend.website.domain.CloudUser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CloudUser_Roo_Configurable {
    
    declare @type: CloudUser: @Configurable;
    
}
